version: "3"

networks:
  dota-league-net:

services:
  traefik:
    image: traefik:v2.9
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      - "--entrypoints.http.http.redirections.entrypoint.to=https"
      - "--entrypoints.http.http.redirections.entrypoint.scheme=https"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=bans.cowboy@gmail.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt:rw
    networks:
      - dota-league-net

  nextjs:
    build: ./nextjs-app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextjs.rule=Host(`radekomsa.site`)"
      - "traefik.http.routers.nextjs.entrypoints=https"
      - "traefik.http.routers.nextjs.tls=true"
      - "traefik.http.routers.nextjs.tls.certresolver=letsencrypt"
      - "traefik.http.services.nextjs.loadbalancer.server.port=3000"
    environment:
      - DATABASE_PATH=/app/db/league.db
      - NEXTAUTH_URL=https://radekomsa.site
      - AUTH_SECRET=5nfxJAUzLoY+m53Qdm/mRXFurIZi0MSDA7+uNBcR9LQ=
      - AUTH_DISCORD_ID=1342432214910238730
      - AUTH_DISCORD_SECRET=6lEc2TH-RYu28Fgt10BqXIXrjlvlpby8
      - ADMIN_IDS=261319928320098304,662288348114845719,246806085111906304
    volumes:
      - ./db:/app/db
    depends_on:
      - traefik
    networks:
      - dota-league-net
    restart: always
