services:
  python:
    build: ./python-scripts
    # Update the command if your file is named differently
    command: bash -c "python discord_db.py && sleep 5 && python run_all_py.py"
    environment:
      - DATABASE_PATH=/app/db/league.db
    env_file:
      - .env.python
    volumes:
      - ./db:/app/db
    restart: "no"

  nextjs:
    build: ./nextjs-app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_PATH=/app/db/league.db
      - NEXTAUTH_URL=http://localhost:3000
      - AUTH_SECRET=5nfxJAUzLoY+m53Qdm/mRXFurIZi0MSDA7+uNBcR9LQ=
      - AUTH_DISCORD_ID=1341423971328852040
      - AUTH_DISCORD_SECRET=PhUIBdLwHC0LmNiQy_JNEPVyq-V5wi5x
    volumes:
      - ./db:/app/db
    depends_on:
      - python
    restart: always
