import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";

import { cn } from "@/lib/utils";
import DashboardPage from "./page";
import { ThemeProvider } from "@/components/theme-provider";
import { MainNav } from "../components/dashboard/main-nav";
import { Search } from "../components/dashboard/search";
import { SignIn } from "../components/dashboard/signIn";
import { ModeToggle } from "../components/ui/ModeToggle";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="border-b">
            <div className="flex h-16 items-center px-4">
              <MainNav className="mx-6" />
              <div className="ml-auto flex items-center space-x-4">
                <ModeToggle />
                <SignIn />
              </div>
            </div>
          </div>
          <div className="p-20">{children}</div>
        </ThemeProvider>
      </body>
    </html>
  );
}
